spring:
  application:
    name: my-app

server:
  port: 8082

eurekaServer: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServer}:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  profiles: dev

eurekaServer: localhost
